<?php

namespace BlogBundle\Form;

use Ivory\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class BlogPostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder->add('title');
        $builder->add('slug', null, ['label' => 'URL']);
        $builder->add('text', CKEditorType::class);
        $builder->add('publishedAt', DateTimeType::class);
        $builder->add('tags', CollectionType::class, [
            'allow_add' => true,
            'prototype' => true,
            'allow_delete' => true,
            'delete_empty' => true,
            'prototype_data' => 'New Tag...',
        ]);
        $builder->add('isActive');
        $builder->add('views', TextType::class, ['disabled' => true]);
        $builder->add('save', SubmitType::class);
    }
}